language: python
python:
  - "2.7"

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio
- platformio lib install 891 # https://platformio.org/lib/show/891/Keyboard

env:
- BOARD=leonardo

script:
- set -eo pipefail;
  for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
