language: python
python:
  - "2.7"

cache:
  directories:
  - "~/.platformio"

install:
- pip install -U platformio

env:
- BOARD=leonardo

script:
- set -eo pipefail;
  for e in examples/*; do
    platformio ci --board=$BOARD --lib=. $e/*;
  done
